$ANSIBLE_VAULT;1.1;AES256
36326530356661343936323466383133353866346230653634326439363832643262356232396633
6231333030656331623533633739393164653165343737310a633365636436346532666430303234
66643330326439623437313261633764656337333937376632633662333939303463646539346234
3230653636366166360a653030663635333963323534316661383034653336343030316538623938
37353265616235623736653938306339336264323865366166366336613565623265616462376334
6233643163353831346432666662636230323462393065303164
