---
# Update Debian based systems
- name: Update and upgrade the system
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full

# Install packages for Debian based systems
- name: Install useful tools
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ system_packages }}"