---
# Include the OS specific variables
- name: Include specific OS variables
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Import debian update playbook
  import_tasks: 'update_debian.yml'
  when: ansible_os_family == 'Debian'

- name: Import debian update playbook
  import_tasks: 'update_redhat.yml'
  when: ansible_os_family == 'RedHat'